### PR TITLE
Fix prop types for react-next

### PR DESCRIPTION
**Pull request by kLabz**
`redux`'s Provider breaks with latest `react-next` (only when using literals) because of its `children` prop type which is too restrictive.

This has no impact when using `haxe-react` instead.

### CODE REVIEW

**Comment by elsassph** [comment]
Looks odd that it would be a fragment here. You sure?

**Comment by kLabz** [comment]
Well, yes and no. It should be `ReactSingleFragment` instead since `Provider` accepts only one child, I'll update this PR.

`ReactFragment` / `ReactSingleFragment`:
https://github.com/kLabz/haxe-react/blob/next/src/lib/react/ReactComponent.hx#L126
https://github.com/kLabz/haxe-react/blob/next/doc/react-next.md#reactfragment

**Comment by elsassph** [comment]
Oh ok it's not the same as `react.Fragment`... 
I can't really merge that until `react-next` becomes the main version I think.

**Comment by kLabz** [comment]
Why? It handles both `react` and `react-next`

**Comment by elsassph** [comment]
Sorry forgot the ifdef

**Pull request merged**
