### PR TITLE
Added support for redux thunk

### PR DESCRIPTION
**Pull request by kLabz**
Redux thunks (from [redux-thunk](https://github.com/gaearon/redux-thunk), more informations on thunks available [here](https://stackoverflow.com/questions/35411423/how-to-dispatch-a-redux-action-with-a-timeout/35415559#35415559)) are not really compatible with haxe-redux, since they work by dispatching functions instead of actions and catching them in a middleware.

This PR reproduces this behavior, but with actual actions (recognized by haxe-redux) and a haxe-redux middleware. There is no need for redux-thunk library, this is "native".

[Example app](https://github.com/kLabz/haxe-redux-todo/tree/redux/thunk)

#### Apply middleware

```haxe

var middleware = Redux.applyMiddleware(
	mapMiddleware(Thunk, new ThunkMiddleware())

	// Or, if you want to add custom data like it is possible with redux-thunk:
	mapMiddleware(Thunk, new ThunkMiddleware({custom: "data"}))
);

return createStore(rootReducer, initialState, middleware);
```

#### Create your thunks

```haxe
class TodoThunk {
	public static function add(todo:String) {
		return Thunk.Action(function(dispatch, getState) {
			return dispatch(TodoAction.Add(todo));
		});
	}

	public static function addIf(todo:String) {
		// Add typing if you want autocompletion and proper typing of your state
		return Thunk.Action(function(dispatch:Dispatch, getState:Void->ApplicationState) {
			var todos = getState().todoList.todos;

			if (Lambda.exists(todos, function(t) return t.text == todo))
				return null;

			return dispatch(TodoAction.Add(todo));
		});
	}

	// If you want to consume the custom data from your thunk:
	public static function dummy() {
		return Thunk.WithParams(function(dispatch, getState, params) {
			trace(params); // {custom: "data"}
			return null;
		});
	}
}
```

#### Use them in a container

```haxe
static function mapDispatchToProps(dispatch:Dispatch) {
	return {
		addTodo: function(todo:String) return dispatch(TodoThunk.add(todo))
	};
}
```

### CODE REVIEW

**Comment by elsassph** [comment]
What about having a `Thunk.createMiddleware()` instead of `mapMiddleware(Thunk, new ThunkMiddleware())`?

**Comment by kLabz** [comment]
`Thunk.createMiddleware()` will not be possible because `Thunk` is an enum.

I'm not sure why you want a shorthand here, since `mapMiddleware` is the documented way of adding middlewares in haxe-redux.

**Comment by elsassph** [comment]
Hum or `ThunkMiddleware.create()` - but but yeah fair enough.
Worth noting that it should be the first middleware.

**Comment by elsassph** [comment]
Oh I kind of overlooked a bit that you're using an enum - I think it will give false expectations to people because the whole point of thunk is that you can dispatch functions and/or promises: if you were to use code that expects that to work you'll be in for a bad surprise.

**Comment by kLabz** [comment]
The surprise would be a compilation error since haxe-redux does not allow you to dispatch functions. That's the point of this PR, actually: allowing you to dispatch `Thunk.Action(myFunction)` (which is longer than just dispatching the function, but close enough).

This is fine if you don't want this in haxe-redux, there is no ties with haxe-redux internals here so it can live on in a tiny additional lib.

**Comment by elsassph** [comment]
Okay. Other crazy idea: could it be handled at the abstract level? So you don't even need to use the enumeration explicitly?

**Comment by kLabz** [comment]
I tried that yesterday (for all `IMiddleware`). No luck for now since `TAction` couldn't be used to get the real Enum hiding behind =/ But I'm not giving up.

Btw, I replaced `Dynamic` with `TAction` in `StoreBuilder` map functions. I did not push a PR for that, but it works on all my projects (should work with every working IReducer/IMiddleware anyway).

**Comment by elsassph** [comment]
Ah no I was suggesting to define `TAction` to accept both enums and functions. But it's maybe that's not feasible to have different abstract constructors.

**Comment by elsassph** [comment]
I'm inclined to go and merge this, but do we need the `WithParams` case? Maybe we can just always pass the params to the callback? Is that a typing problem?

**Comment by kLabz** [comment]
Yes, I don't think haxe would unify a callback missing the optional argument, so we'd need to handle params in all callbacks (WithParams being a pretty rare feature, it doesn't seem to be worth the trouble; I only added it because redux-thunk has it).

**Pull request merged**
